[tool.poetry]
name = "llama_cpp"
version = "0.1.0"
description = "Python bindings for the llama.cpp library"
authors = ["Andrei Betlen <abetlen@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/abetlen/llama_cpp_python"
repository = "https://github.com/abetlen/llama_cpp_python"
packages = [{include = "llama_cpp"}]
include = [
    "LICENSE.md",
]

[tool.poetry.dependencies]
python = "^3.8.1"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
