# Based on: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Publish to TestPyPI

on: workflow_dispatch

jobs:
  build-n-publish:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "true"
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Update __version__ with Git Short Hash
      run: sed -i "s/__version__ = .*/__version__ = '$(git rev-parse --short HEAD)'/" llama_cpp/__init__.py
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip build
        python3 -m pip install -e .[all]
    - name: Build source distribution
      run: |
        python3 -m build --sdist
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/